development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thin_core_development
  pool: 5
  username: root
  password: 'hungry'
  socket: /var/run/mysqld/mysqld.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thin_core_staging
  pool: 5
  username: root
  password: 'hungry'
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thin_core_production
  pool: 5
  username: root
  password: 'hungry'
  socket: /var/run/mysqld/mysqld.sock
